### ISSUE TITLE
Handling title strings with %-encoded hex sequences

### ISSUE THREAD

**Issue by subbuss** [wikimedia/mediawiki-title#7]
[[7%25 solution]] as well as [[7% solution]] are valid wikitext and both link to "7%_solution" in a enwiki sandbox.

However, right now, mediawiki-title rejects "7%25 solution" as an invalid title. The question is whether %-encoded hex sequences should be url-decoded in Title.newFromText, be controlled by an option, or if users of mediawiki-title should do this url-decoding before invoking Title.newFromText.

We should adjust RESTBase and Parsoid uses of mediawiki-title based on how we resolve this and update documentation for mediawiki-title accordingly.

**Comment by subbuss** [comment]
@cscott  you might have an opinion as well as a potential user of mediawiki-title for ocg.

**Comment by Pchelolo** [comment]
The problem with RB is that the title parameter is transparently url-decoded way before we get to using the lib. Obviously, adding one more `decodeURIComponent` is wrong as it will cause the whole bunch of problems with titles containing `%` symbol. 

So, if we decide to put a `decodeURIComponent` call into the lib, we should make it optional and controlled by a boolean flag.

**Comment by cscott** [comment]
Yes, you can't use stock url-decoding because MW doesn't do it that way.  You probably need to export a `decodeMWURIComponent` API or something like that, maybe just an optional `mwdecode` flag, in order to decode titles "the same way MW does".

**Comment by cscott** [comment]
@subbuss from ocg's perspective, I don't need to deal with the URI craziness, since that's a feature of wikitext, not Parsoid DOM.  OCG deals with DOM, and I can "trust" that (after entity decoding) the string in the href is a representation of the true title.

I would say that handling `[[7%25 solution]]` is a function of the wikitext parser.  The true title is `7% solution`, not `7%25 solution`, it just happens to have multiple equivalent representations in wikitext.

**Comment by brion** [comment]
IIRC we originally supported the percent-encoding in links to handle interwiki links back before everything had moved to UTF-8. This meant that it wasn't possible to write, say, ```[[ru:Россия]]``` on English Wikipedia (which was in Latin-1 encoding) so you had to write ```[[ru:%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F]]```, which back then was also what you saw in browsers' URL bars, for easy copy-paste.

(The ```[[7% solution]]``` / ```[[7%25 solution]]``` example was an English example for testing, to make sure we could distinguish the URL-encoded and non-URL encoded cases without breaking.)

But it's really not part of a title parser -- it's normalization applied on wiki link processing. That's why you find it in Title::newFromText(), which handles titles coming from wikitext -- but not in Title::newFromURL(), which handles the page title that came in from the URL (already URL-decoded by higher levels of processing).

I'm not sure it's really something that _should_ be done in ..... anywhere other than wiki link processing ...... but for historical compatibility reasons probably have to keep it in many places.

**Comment by brion** [comment]
Note also that the PHP-side Title::secureAndSplit() and JS-side _createInvalidTitleRegex() specifically forbid % followed by two hex digits in valid titles, so there is no danger of Title::newFromText() / Title.newFromText() mangling otherwise-valid input here if you do the decoding.

**Comment by subbuss** [comment]
Thanks for that useful context @brion. As for "so there is no danger of Title::newFromText() / Title.newFromText() mangling otherwise-valid input here if you do the decoding.", I think @Pchelolo's worry was about mangling otherwise-*invalid* input (Ex: 7%2525 => 7%25 => 7%)

**Comment by subbuss** [comment]
Based on @brion's and @cscott 's comments, I am going to proceed with doing this in Parsoid especially since mediawiki-title doesn't handle subpages, fragments and there is fragment test that involves hex entities (see parserTest 'Link containing "#<" and "#>" % as a hex sequences- these are valid section anchors') and the fragment parts need url-decoding as well.

**Comment by Pchelolo** [comment]
@subbuss I haven't added the frament support here simply because we don't need it in RESTBase - all we need is to strip out the fragment, however I think supporting fragment normalisation should end up inside the lib.

What do you mean by subpages support? Should there be some specialised support for subpages I was not aware of?

**Comment by subbuss** [comment]
I'll submit PRs once I have all this code working in Parsoid. :-)

As for subpages, yes, you need url resolution .. see the resolveTitle code in https://gerrit.wikimedia.org/r/#/c/281037/8/lib/config/MWParserEnvironment.js --- that code is still change as I am working through parser test failures and fixing up things.

**Comment by Pchelolo** [comment]
@subbuss Ok, great, thank you. I hope the lib doesn't lack too many features :) 

I think we can close this articular ticket as it's original purpose is solved - we know what to do with `7%25` now. If you don't agree - please reopen it.
